### ISSUE TITLE
Broken array in core.process_psd()

### ISSUE THREAD

**Issue by sblanky** [sblanky/pyPUC#1]
`Traceback (most recent call last):
  
File "/gpfs01/home/pcxtsbl/.conda/envs/pyPUC/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  
File "/gpfs01/home/pcxtsbl/.conda/envs/pyPUC/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
 
 File "/gpfs01/home/pcxtsbl/pyPUC/pyPUC/0060_all_log.py", line 42, in <module>
    parameter_df, data_dict = process_psd(project, psd_sorptive, parameter, now,
 
File "/gpfs01/home/pcxtsbl/pyPUC/pyPUC/core/psd_processing.py", line 255, in process_psd
    param_df = parameter_df(data_dict, w_array,

File "/gpfs01/home/pcxtsbl/pyPUC/pyPUC/core/psd_processing.py", line 201, in parameter_df
    param = find_parameter(data_dict[d], measure=measure,

File "/gpfs01/home/pcxtsbl/pyPUC/pyPUC/core/psd_processing.py", line 139, in find_parameter
    rows_min = np.max(list(np.where(w<wmin)))

File "<__array_function__ internals>", line 5, in amax

File "/gpfs01/home/pcxtsbl/.conda/envs/pyPUC/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2754, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,

File "/gpfs01/home/pcxtsbl/.conda/envs/pyPUC/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: zero-size array to reduction operation maximum which has no identity`

**Comment by sblanky** [comment]
fixed: [`cd18575`](https://github.com/sblanky/pyPUC/commit/cd18575649158f2b49f38f7e040681845fdd906e)
